// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/15/2025, 4:15:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["G:/99.Github/nuxt-docs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/plugins/**/*.{js,ts,mjs}","G:/99.Github/nuxt-docs/composables/**/*.{js,ts,mjs}","G:/99.Github/nuxt-docs/utils/**/*.{js,ts,mjs}","G:/99.Github/nuxt-docs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/nuxt-docs/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;